# name: Node js Express CI/CD

on:
  push:
    branches: [main]
    paths:
      - '/backend/express/**'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Chekout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: restart pm2
        run: pm2 restart build/server.js